"""OWASP Threat Dragon v2 emitter.

Produces a single JSON document conforming to TD v2's model schema. Cells use
auto-generated UUIDs (UUIDv5 derived stably from ArchiMate IDs so re-runs
produce identical outputs). Layout is deterministic auto-layout: zones laid
out left-to-right, components placed at absolute coordinates inside each zone,
flows reference cell IDs.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from typing import Any

from ..model import MappedComponent, MappedConnection, MappedModel, MappedZone

TARGET_ID = "threatdragon"

# Stable UUIDv5 namespace for archithreat → TD cell ID derivation.
_NAMESPACE = uuid.UUID("8b1cf3c0-9d68-4c4f-9f1f-cb6b3ac2ed01")

# Layout constants (px)
ZONE_PADDING = 40
ZONE_HEADER = 30
COMPONENT_W = 120
COMPONENT_H = 80
COMPONENT_GAP = 30
ZONE_GAP = 60
ZONE_TOP = 40
ZONE_LEFT = 40
ROWS_PER_ZONE = 3


def _cid(original: str) -> str:
    """Stable UUIDv5 from ArchiMate ID."""
    return str(uuid.uuid5(_NAMESPACE, original))


@dataclass
class _PlacedCell:
    """Internal accumulator before serializing to JSON."""

    cid: str
    component: MappedComponent
    x: int
    y: int


class ThreatDragonEmitter:
    target_id: str = TARGET_ID
    output_extension: str = "json"
    output_media_type: str = "application/json"

    def emit(self, model: MappedModel) -> bytes:
        from . import EmitterError

        # Layout: left-to-right zones; components laid out in a grid inside each.
        zones = sorted(model.zones.values(), key=lambda z: z.zone.name.lower())
        layouts = _layout(zones, model)

        cells: list[dict[str, Any]] = []

        # 1. Trust boundary boxes (zIndex -50 so they render behind components).
        for layout in layouts:
            cells.append(_zone_cell(layout))

        # 2. Components inside zones.
        placed: dict[str, _PlacedCell] = {}
        for layout in layouts:
            for placement in layout.placements:
                cid = _cid(placement.component.component.id)
                placed[placement.component.component.id] = _PlacedCell(
                    cid=cid,
                    component=placement.component,
                    x=placement.x,
                    y=placement.y,
                )
                cells.append(_component_cell(cid, placement))

        # 3. Flows.
        for mconn in model.connections:
            conn = mconn.connection
            src = placed.get(conn.source_component_id)
            tgt = placed.get(conn.target_component_id)
            if src is None or tgt is None:
                continue
            cells.append(_flow_cell(mconn, src.cid, tgt.cid))

        diagram = {
            "id": _cid(model.source_name or "archithreat"),
            "title": model.source_name or "archithreat",
            "diagramType": "STRIDE",
            "version": "2.0.0",
            "thumbnail": "/content/images/thumbnail.stride.jpg",
            "cells": cells,
        }

        out = {
            "version": "2.0.0",
            "summary": {
                "title": model.source_name or "archithreat",
                "owner": "",
                "description": "Generated by archithreat from ArchiMate Open Exchange XML.",
                "id": 0,
            },
            "detail": {
                "contributors": [],
                "diagrams": [diagram],
                "diagramTop": 0,
                "reviewer": "",
                "threatTop": 0,
            },
        }

        payload = json.dumps(out, indent=2, sort_keys=True).encode("utf-8")
        _validate(payload, raise_cls=EmitterError)
        return payload


# ---------- Layout ----------


@dataclass
class _Placement:
    component: MappedComponent
    x: int
    y: int
    w: int = COMPONENT_W
    h: int = COMPONENT_H


@dataclass
class _ZoneLayout:
    mapped_zone: MappedZone
    x: int
    y: int
    w: int
    h: int
    placements: list[_Placement] = field(default_factory=list)


def _layout(zones: list[MappedZone], model: MappedModel) -> list[_ZoneLayout]:
    """Lay zones out left-to-right; components in a grid inside each zone."""
    by_zone: dict[str, list[MappedComponent]] = {}
    for mc in model.components.values():
        by_zone.setdefault(mc.component.zone_id, []).append(mc)
    for k in by_zone:
        by_zone[k].sort(key=lambda m: (m.component.name.lower(), m.component.id))

    layouts: list[_ZoneLayout] = []
    cursor_x = ZONE_LEFT
    for mz in zones:
        members = by_zone.get(mz.zone.id, [])
        cols = max(1, min(ROWS_PER_ZONE, len(members)))
        rows = (len(members) + cols - 1) // cols if members else 1
        zone_w = max(
            cols * COMPONENT_W + (cols + 1) * COMPONENT_GAP,
            COMPONENT_W + 2 * COMPONENT_GAP,
        )
        zone_h = max(
            ZONE_HEADER + rows * COMPONENT_H + (rows + 1) * COMPONENT_GAP,
            COMPONENT_H + ZONE_HEADER + 2 * COMPONENT_GAP,
        )
        layout = _ZoneLayout(mapped_zone=mz, x=cursor_x, y=ZONE_TOP, w=zone_w, h=zone_h)
        for i, mc in enumerate(members):
            row = i // cols
            col = i % cols
            cx = cursor_x + COMPONENT_GAP + col * (COMPONENT_W + COMPONENT_GAP)
            cy = ZONE_TOP + ZONE_HEADER + COMPONENT_GAP + row * (COMPONENT_H + COMPONENT_GAP)
            layout.placements.append(_Placement(component=mc, x=cx, y=cy))
        layouts.append(layout)
        cursor_x += zone_w + ZONE_GAP
    return layouts


# ---------- Cell builders ----------


def _zone_cell(layout: _ZoneLayout) -> dict[str, Any]:
    spec = layout.mapped_zone.target_data.get("threatdragon", {})
    if not isinstance(spec, dict):
        spec = {}
    return {
        "id": _cid(layout.mapped_zone.zone.id),
        "shape": "trust-boundary-box",
        "zIndex": -50,
        "position": {"x": layout.x, "y": layout.y},
        "size": {"width": layout.w, "height": layout.h},
        "attrs": {
            "body": {
                "rx": int(spec.get("rx", 10)),
                "ry": int(spec.get("ry", 10)),
                "strokeWidth": int(spec.get("stroke_width", 3)),
                "strokeDasharray": str(spec.get("stroke_dasharray", "10 5")),
                "stroke": str(spec.get("stroke_color", "#333333")),
                "fill": "transparent",
                "fillOpacity": 0,
            },
            "label": {
                "text": layout.mapped_zone.zone.name,
                "textAnchor": "bottom",
                "textVerticalAnchor": "top",
                "refX": "15%",
                "refY": "12",
            },
        },
        "data": {
            "type": "tm.BoundaryBox",
            "name": layout.mapped_zone.zone.name,
            "description": "",
            "isTrustBoundary": True,
            "hasOpenThreats": False,
        },
    }


def _component_cell(cid: str, placement: _Placement) -> dict[str, Any]:
    mc = placement.component
    spec = mc.target_data.get("threatdragon", {})
    if not isinstance(spec, dict):
        spec = {}
    shape = str(spec.get("shape", "process"))
    type_name = str(spec.get("type_name", "tm.Process"))
    name = mc.component.name
    passthrough = mc.target_data.get("passthrough_properties", {})
    if not isinstance(passthrough, dict):
        passthrough = {}

    cell: dict[str, Any] = {
        "id": cid,
        "shape": shape,
        "zIndex": 1,
        "position": {"x": placement.x, "y": placement.y},
        "size": {"width": placement.w, "height": placement.h},
        "attrs": _component_attrs(shape, name),
        "data": _component_data(shape, type_name, name, spec, passthrough),
    }
    return cell


def _component_attrs(shape: str, name: str) -> dict[str, Any]:
    text = {"text": name}
    if shape == "store":
        return {
            "text": text,
            "topLine": {
                "stroke": "#333333",
                "strokeWidth": 1,
                "strokeDasharray": None,
            },
            "bottomLine": {
                "stroke": "#333333",
                "strokeWidth": 1,
                "strokeDasharray": None,
            },
        }
    return {
        "text": text,
        "body": {
            "stroke": "#333333",
            "strokeWidth": 1,
            "strokeDasharray": None,
        },
    }


def _component_data(
    shape: str,
    type_name: str,
    name: str,
    spec: dict[str, Any],
    passthrough: dict[str, Any],
) -> dict[str, Any]:
    base: dict[str, Any] = {
        "name": name,
        "type": type_name,
        "description": "",
        "outOfScope": bool(spec.get("out_of_scope", False)),
        "reasonOutOfScope": "",
        "hasOpenThreats": False,
        "threats": [],
        "isTrustBoundary": False,
    }
    if shape == "process":
        base.update(
            {
                "isWebApplication": bool(spec.get("is_web_application", False)),
                "privilegeLevel": str(spec.get("privilege_level", "")),
                "handlesCardPayment": bool(spec.get("handles_card_payment", False)),
                "handlesGoodsOrServices": bool(spec.get("handles_goods_or_services", False)),
            }
        )
    elif shape == "store":
        base.update(
            {
                "isEncrypted": bool(spec.get("is_encrypted", False)),
                "isSigned": bool(spec.get("is_signed", False)),
                "isALog": bool(spec.get("is_a_log", False)),
                "storesCredentials": bool(spec.get("stores_credentials", False)),
                "storesInventory": bool(spec.get("stores_inventory", False)),
            }
        )
    elif shape == "actor":
        base.update(
            {
                "providesAuthentication": bool(spec.get("provides_authentication", False)),
            }
        )
    if passthrough:
        # Surface passthrough properties on the cell's data block as a
        # nested map; TD ignores unknown fields.
        base["archithreatProperties"] = dict(passthrough)
    return base


def _flow_cell(mconn: MappedConnection, src_cid: str, tgt_cid: str) -> dict[str, Any]:
    spec = mconn.target_data.get("threatdragon", {})
    if not isinstance(spec, dict):
        spec = {}
    passthrough = mconn.target_data.get("passthrough_properties", {})
    if not isinstance(passthrough, dict):
        passthrough = {}
    protocol = str(spec.get("protocol") or passthrough.get("protocol") or "")
    encryption = passthrough.get("encryption", "").lower()
    is_encrypted = bool(spec.get("is_encrypted", False)) or encryption in {
        "tls",
        "mtls",
        "ssl",
    }
    is_public_network = bool(spec.get("is_public_network", False))
    return {
        "id": _cid(mconn.connection.id),
        "shape": "flow",
        "zIndex": 10,
        "source": {"cell": src_cid},
        "target": {"cell": tgt_cid},
        "connector": "smooth",
        "attrs": {
            "line": {
                "stroke": str(spec.get("stroke_color", "#333333")),
                "strokeWidth": int(spec.get("stroke_width", 1)),
                "targetMarker": {"name": "block"},
                "strokeDasharray": None,
            }
        },
        "data": {
            "type": "tm.Flow",
            "name": mconn.connection.id,
            "description": "",
            "protocol": protocol,
            "isEncrypted": is_encrypted,
            "isPublicNetwork": is_public_network,
            "outOfScope": False,
            "reasonOutOfScope": "",
            "hasOpenThreats": False,
            "threats": [],
        },
    }


# ---------- Validation ----------


def _validate(payload: bytes, raise_cls: type[Exception]) -> None:
    try:
        doc = json.loads(payload)
    except json.JSONDecodeError as exc:
        raise raise_cls(f"Emitted JSON malformed: {exc}") from exc
    if doc.get("version") != "2.0.0":
        raise raise_cls("Top-level version must be 2.0.0")
    detail = doc.get("detail")
    if not isinstance(detail, dict):
        raise raise_cls("Missing 'detail' object")
    diagrams = detail.get("diagrams")
    if not isinstance(diagrams, list) or not diagrams:
        raise raise_cls("'detail.diagrams' must be a non-empty list")
    diagram = diagrams[0]
    cells = diagram.get("cells")
    if not isinstance(cells, list):
        raise raise_cls("'diagram.cells' must be a list")

    cell_ids = {c.get("id") for c in cells if isinstance(c, dict)}
    for c in cells:
        if not isinstance(c, dict):
            raise raise_cls(f"Cell entry is not an object: {c!r}")
        cid = c.get("id")
        if not isinstance(cid, str) or not cid:
            raise raise_cls("Cell missing string id")
        shape = c.get("shape")
        if shape == "flow":
            for endpoint in ("source", "target"):
                ep = c.get(endpoint)
                if not isinstance(ep, dict) or "cell" not in ep:
                    raise raise_cls(f"Flow {cid!r} has malformed {endpoint} endpoint")
                if ep["cell"] not in cell_ids:
                    raise raise_cls(
                        f"Flow {cid!r} references unknown {endpoint} cell {ep['cell']!r}"
                    )


__all__ = ["TARGET_ID", "ThreatDragonEmitter"]
